db:   #database service
  drivername : "mysql"
  username : "perennial"
  password : "perennial"
  host : "database"     #use when running in docker and host will change as per service name change of database in docker compose
  #host : "0.0.0.0"     #uncomment when you are running host 0.0.0.0
  port : "3306"
  dbname : "userRepository"
userrepo:
  port : ":8084"
key:
  jwtKey: "perennial"
