db:
  drivername : "mysql"
  username : "perennial"
  password : "perennial"
  #host : "localhost"    #uncomment when you are running application on local machine
  host : "database"      #use when running in docker and host will change as per service name change of database in docker compose
  port : "3306"
  dbname : "userRepository"
userrepo:
  port : ":8084"
